### PR TITLE
Fix HTTP in links

### LINKED ISSUE #436: Change Imgur HTTP links to HTTPS
## The Problem
According to WEB-3002, imgur links sometimes load through HTTP instead of HTTPS. This causes the site to think that the user's connection is not secure.
## Possible Solution
Switch any Imgur links using HTTP to HTTPS to remove the warning

### PR DESCRIPTION
**Pull request by chandler05**
## Purpose
Closes #436 
## Approach
Replaces HTTP: in all links to HTTPS:

### CODE REVIEW

**Comment by chandler05** [comment]
Is it fine to convert this for all links? Let me know if the HTTP needs to be changed only on imgur link, because right now it matches all Http: links

**Comment by SPGoding** [comment]
I guess only a list of websites need to be replaced with HTTPS (see #437 for more information).

We could possibly maintain a list of trusted URLs in the config, create two regular expressions in the `ReplaceText` module from that list to solve the two issues mentioned in #437, and of course write a bunch of tests ;D

**Comment by chandler05** [comment]
This could also potentially solve #385 by including a list of trusted links we no longer need to check for a link taking you to a bad website.

Anyone who's good at Regex feel free to contribute. It took me around 30 minutes to get the small Regex for this PR

List of trusted sites:
- Bug tracker (obviously)
- Jira/Atlassian (for WEB project)
- Reddit
- Discord
- Imgur
- YouTube
- Streamable
- Minecraft.net
- GitHub

Add others to the list! (I'll edit it with any new websites)

**Comment by dericksonmark** [comment]
Hi! Maybe add OBS; it's in the helper message Attach video (PC). Also for Discord links, make sure you include discordapp.com and discord.gg, as they're both used in helper messages.

**Comment by NeunEinser** [comment]
What do you mean with trusted URLs?
I don't think we need to restrict domains. Personally, I never encountered a bad link and this is probably gonna cause more harm than good.
The module that was proposed a while ago, which removes misleading urls is sufficient imo.

And yes, you shouldn't just replace http with https in general. Some sites still don't have the https protocol implemented, slicedlime.tv is an example of that. You can't connect using https, only http.

**Comment by chandler05** [comment]
For now, I'm going to switch it to only Imgur links and then this PR can be reviewed/merged. The other module can be created separately

**Review by urielsalis — APPROVED** [review]

**Comment by urielsalis** [comment]
Please open a new issue for adding more sites

**Pull request merged**
